services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
